settings:
    # general plugin settings
    # if you don't want deciamls ($1.23)
    wholeNumberRewards: false
    # if only direct player kills gives reward (disables mob farming)
    #  (this is ignored if on a disabled world or region)
    onlyKillDrop: false
    # if replaceDrop, then default drops are removed & substituted
    #   if false, custom drops are added to the existing drops
    replaceDrops: false
    # if onlyKillDrop: false, should custom drops always occur?
    alwaysReplaceDrops: true
    # if allow hunting with wolves
    allowWolfHunt: true
    #disable damage if can't afford to kill? (applies to wolves, too)
    disableExpensiveKill: true
    # any world listed here won't be checked (comma-delimited, case-insensitive)
    disableWorlds: testWorld1, world2, random_world_nether
    # if any regions are defined, should they be disabled regions or the only places cm is enabled?
    # true (default): regions are areas where cm is disabled
    #     (however, regions on disabled worlds are reversed & will be enabled)
    # false: cm is globally disabled, except for within regions (disabled worlds ignored)
    regionsDisable: true
    # for how long a player is 'protected' from spawn camping
    #		(player kill rewards are nulled)
    playerRewardWait: 1m
    # if a player killed within the playerRewardWait period
    #		reward is reversed (in case of positive reward only)
    #		eg. player who kills the player pays amount
    playerReverseProtect: true
    # if the players who die pay the killer (assuming has enough)
    playerPaysReward: true
    # optional multiplier for dropped exp
    expMultiplier: 1

#spawn camp tracking occurs when a player kills a monster
spwanCampTracking:
    # if enabled, there are no rewards (or drops) after the threshold is passed
    enabled: false
    # if global is enabled, will apply camp tracking to "natural" deaths
    #   this would allow monsters to drop items naturally, but disable monster killing machines
    #   (player drops are preserved, though, to protect the innocent)
    global: false
    # if suspected camping kills won't drop items
    disableDrops: true
    # if also disabled exp drops
    disableExp: true
    # elevation change max
    deltaY: 5
    # square about center (distance from center to edge)
    deltaX: 20
    # time before a kill is no longer counted against tracking
    #   positive integer values only, units being m(inutes) h(hours) d(ays) w(eeks) M(onths) (default: m)
    timeout: 20m
    # max kills in the area before counted as spawn camping
    campKills: 50

# any LivingEntity listed here can have it's own rewards
# can give a range for economy reward ( min-max )
# itemCoins to give custom ranges for individual items (note: durability not supported for items here)
# can configure custom drops for each (origional drops are replaced with these, so 0%0 would disable rewards)
# drops syntax: itemID[:subData][@maxDrop]%Probability[,another drop... ]
## 100 Probability means will drop each time
## if = 50, only means 50% chance of drop, chance of full drop is random
rewards:
    Chicken: 
        drops: 344%10, 288@2%70
    Cow:
    Creeper:
        drops: 2256@1%.5, 289@4%80
        coins: 1-4
        # itemCoins example: bow&arrow give no reward, wooden sword is worth more
        itemCoins: "261>0, 268>3-6"
    Charged_Creeper:
        drops: 2256@1%2, 289@5%90
        coins: 2-8
        # itemCoins example: bow&arrow give no reward, wooden sword is worth more
        itemCoins: "261>0, 268>5-16"
    Ghast:
        drops:
        coins: 2-5
    Giant:
        # giant zombie, not very likely to encounter
    Monster:
        # this is a fake human, not likely to occur
    Pig:
    PigZombie:
        drops: 320@2%70, 283%01
        coins: 2-3
    Sheep:
    Skeleton:
        drops: 261@1%10, 262@4%80
        coins: 1-3
    Slime:
        drops:
        coins: 1-2
    Spider:
        drops:
        coins: 1-2
    Squid:
    Zombie:
        drops:
        coins: 1-2
    Wild_Wolf:
        drops:
        coins: -1--2
    Tame_Wolf:
        drops:
        coins: -5--10
    Pet_Wolf:
        # this applies if you kill a wolf that is your own
        drops:
        coins: 
    Enderman:
        drops:
        coins: 1-2
    Silverfish:
        drops:
        coins: 1-2
    Cave_Spider:
        drops:
        coins: 1-2
    Ender_Dragon:
        drops:
        coins: 100-500
    Villager:
        drops:
        coins: 0
    Blaze:
        drops:
        coins: 2-4
    Mushroom_Cow:
        drops:
        coins: 0
    Magma_Cube:
        drops:
        coins: 1-2
    Snow_Golem:
        drops:
        coins: -1--2
    MobSpawner:
        drops:
        coins: -4--5
    Player:
        coins: 0
        drops:


        
messages:
    # Colors are specified by using "&[colorcode]".
    #     (Never put colors within the angle brackets of a tag)
    #   Color table:
    #       &0 is black
    #       &1 is dark blue
    #       &2 is dark green
    #       &3 is dark sky blue
    #       &4 is red
    #       &5 is magenta
    #       &6 is gold or amber
    #       &7 is light grey
    #       &8 is dark grey
    #       &9 is medium blue
    #       &a is light green
    #       &b is cyan
    #       &c is orange-red
    #       &d is pink
    #       &e is yellow
    #       &f is white
    # (use && for a & symbol)

    # rewarded for killing a monster:
    # <amount>  how much credited to account
    # <monster> name of the creature killed
    # <item>    what used to kill it
    reward: "&a You are rewarded &f<amount>&a for killing the &f<monster>"
    # if the reward is specific to what the user is holding
    itemreward: "&a You are rewarded &f<amount>&a for killing the &f<monster>&a with a &f<item>"
    # for killing a player
    playerreward: "&a You are rewarded &f<amount>&a for killing the Player &f<player>"
    itemplayerreward: "&a You are rewarded &f<amount>&a for killing the Player &f<player>&a with a &f<item>"
    # for the victim of the attacks
    victimpay: "&f <player>&c took &f<amount>&c from you when you died"
    victimprotection: "&f <player>&a payed you &f<amount>&a as penalty for killing you"
    # this is for when a reward is withheld for suspected spawn camping
    nocampingreward: "&a No more rewards avaliable for this area.. Try again later"
    
    # penalized for killing a monster (if coin range is negative)
    # <amount>  how much removed from account
    # <monster> name of the creature killed
    penalty: "&c You are penalized &f<amount>&c for killing the &f<monster>"
    # <item>    what used to kill it
    itempenalty: "&c You are penalized &f<amount>&c for killing the &f<monster>&c with a &f<item>"
    
    # penalized for killing a player
    # <amount>  how much removed from account
    # <player> name of the player killed
    playerpenalty: "&c You are penalized &f<amount>&c for killing Player &f<player>"
    # penalized for killing a player within the spawn protection
    # <time> spawn protection time (seconds)
    playercamppenalty: "&c You are penalized &f<amount>&c for killing &f<player>&c during spawn protection"
    # <item>    what used to kill
    itemplayerpenalty: "&c You are penalized &f<amount>&c for killing &f<player>&c during spawn with a &f<item>"
    itemplayercamppenalty: "&c You are penalized &f<amount>&c for killing &f<player>&c during spawn with a &f<item>"
    
    # if cannot afford the penalty for killing the entity
    notafford: "&c You cannot afford to kill a &f<monster>"
    itemnotafford: "&c You cannot afford to kill a &f<monster>&c with a &f<item>"
    
    # if no money rewarded (can be blank for none)
    norewardMonster: "&c there is no reward for killing a &f<monster>"
    norewardCreature: 
    norewardPlayer:
    # <item>    what used to kill it
    itemnorewardMonster: "&c there is no reward for killing a &f<monster>&c with a &f<item>"
    itemnorewardCreature: 
    itemnorewardPlayer:

